export const FETCH_CATS = "FETCH_CATS"
export const FETCH_CATS_START = "FETCH_CATS_START"
export const FETCH_CATS_SUCCESS = "FETCH_CATS_SUCCESS"
export const FETCH_CATS_ERROR = "FETCH_CATS_ERROR"

export const FETCH_CAT = "FETCH_CAT"
export const FETCH_CAT_START = "FETCH_CAT_START"
export const FETCH_CAT_SUCCESS = "FETCH_CAT_SUCCESS"
export const FETCH_CAT_ERROR = "FETCH_CAT_ERROR"